name: Linux Release

on:
  push:
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: I dunno...
        shell: bash
        run: echo "I am 'Linux Release'"
