name: Linux Release

on:
  push:
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Define release identifier
        id: vars
        run: echo "release=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Create release if it does not already exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh release create --title ${{ steps.vars.outputs.release }} ${{ steps.vars.outputs.release }}; then
            echo "gh release create failed: assume release already exists"
          fi
        shell: bash
      - name: Upload Linux version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: compress artifact with zstd?
        run: gh release upload --clobber ${{ steps.vars.outputs.release }} ./fake-build-artifacts/linux-release.py
