name: Linux Release

on:
  push:
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Define release identifier
        id: vars
        run: echo "release=${GITHUB_REF#refs/tags/}" >> $GITHUB_STATE
      - name: Check or create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh release view ${{ steps.vars.outputs.release }}; then
            gh release create --title ${{ steps.vars.outputs.release }} ${{ steps.vars.outputs.release }}
          fi
        shell: bash
      - name: Upload Linux version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: compress artifact with zstd?
        run: gh release upload --clobber ${{ steps.vars.outputs.release }} ./fake-build-artifacts/linux-release.py
