name: Linux Release

on:
  push:
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # TODO: compress artifact with zstd?
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Debug VERSION
        run: VERSION=${GITHUB_REF#refs/tags/} echo "$VERSION"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: VERSION=${GITHUB_REF#refs/tags/} gh release view "$VERSION" || gh release create --title "$VERSION" "$VERSION"
      - name: Upload Linux version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber ${GITHUB_REF#refs/tags/} ./fake-build-artifacts/linux-release.py
