name: Linux Release

on:
  push:
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # TODO: compress artifact with zstd?
      - name: Upload Linux version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber ${GITHUB_REF#refs/tags/} ./fake-build-artifacts/linux-release.py
