name: macOS Release

on:
  push:
    tags:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create release
        run: VERSION=${GITHUB_REF#refs/tags/} gh release view "$VERSION" || gh release create --title "$VERSION" "$VERSION"
      - name: Upload macOS version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber ${GITHUB_REF#refs/tags/} ./fake-build-artifacts/macos-release.py
