on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: bolinfest/hello-world-composite-action@v2
        with:
          who-to-greet: 'Lester the Tester'
          platforms:
            linux-x86_64:
              propA: 'propA'
              propB: 'propB'
            macos-x86_64:
              propC: 'propC'
              propD: 'propD'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
