name: aggregate-executables

on:
  # Can we trigger on the "latest" tag being changed or some other tag?
  workflow_run:
    workflows: [Linux Release, macOS Release]
    types:
      - completed

jobs:
  aggregate_executables_job:
    name: Aggregate the executables
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: bolinfest/hello-world-composite-action@v26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-config: .github/workflows/executables.json
          tag: ${{ github.event.workflow_run.head_branch }}
      - name: Verify file was written
        run: cat "${{ github.workspace }}/manifest.jsonc"
